### ISSUE TITLE
Le bureau redessine ses icônes par dessus l'alerte affichée par une appli lancée

### ISSUE THREAD

**Issue by vinz6751** [Landemarre/MyAES#1]
Environnement: STEEM SSE 4.0, MiNT 1.12, TeraDesk 4.07, MyAES du 17-Janvier 2021 16:34

J'ai fait un programme basique qui affiche juste une form_alert avec le PATH de l'AES dedans. Je le lance depuis Teradesk. J'ai remarqué qu'après avoir lancé mon petit programme, Teradesk déselectionne l'icône et redessine, mais ça redessine par dessus ma boîte de dialogue.

![image](https://user-images.githubusercontent.com/9577963/105628895-fc133580-5e3f-11eb-8572-63725a856bbb.png)

**Comment by Landemarre** [comment]
C'est maintenant fixé, je clôture
