### ISSUE TITLE
Les boutons de l'ascenseur du sélecteur de fichiers sont en "3D" 

### ISSUE THREAD

**Issue by vinz6751** [Landemarre/MyAES#2]
Environnement: STEEM SSE 4.0, MiNT 1.12, TeraDesk 4.07, MyAES du 17-Janvier 2021 16:34

![image](https://user-images.githubusercontent.com/9577963/105628963-717f0600-5e40-11eb-9b12-91439d8438e3.png)

**Comment by vinz6751** [comment]
Réponse d'Olivier:
Ah ok c'est celui là, il y en a 2 dans MyAES 1 interne et 1 externe, en fonction de la mémoire disponible ou des options l'un ou l'autre apparaît, c'est celui interne il est vrai que je ne le vois pas souvent! Ok je vais voir cela, c'est pas très beau, cela a le bon ton d'exister et d'être assez compatible avec celui du TOS

**Comment by Landemarre** [comment]
Le sélecteur de fichier interne de secours est maintenant corrigé, en plus des boutons mal positionnés, la partition P restait sélectable même si le drive n'existait pas a été corrigé, le selecteur est aussi légèrement plus beau (son but étant pour machine avec très peu de mémoire, ce sélecteur reste très basic).
Sélecteur corrigé en noir et blanc:
![selectnb](https://user-images.githubusercontent.com/25240527/105642870-b3359e00-5e8c-11eb-8a30-b4b9181f3559.png)
Sélecteur en 16 couleurs :
![select](https://user-images.githubusercontent.com/25240527/105642878-c8123180-5e8c-11eb-81c4-f695538a3346.png)
