### ISSUE TITLE
Avec Pure C, la barre noire en dessous du menu se raffiche même quand le menu est caché

### ISSUE THREAD

**Issue by vinz6751** [Landemarre/MyAES#3]
Environnement: STEEM SSE 4.0, MiNT 1.12, TeraDesk 4.07, MyAES du 17-Janvier 2021 16:34

J'ai noté qu'avec PureC, la barre noire horizontale en dessous de la barre de menu se redessine tout le temps, même quand la barre de menu est cachée, mais je ne sais pas si c'est PureC qui fait ça.

![image](https://user-images.githubusercontent.com/9577963/105629000-b86cfb80-5e40-11eb-955c-2e175e75614c.png)

**Comment by vinz6751** [comment]
Réponse d'Olivier:

Ah oui cela je sais, j'ai cherché, semble que ce soit PureC qui fasse cela c'est curieux, si cela te gène on peut mettre l'option:

app_single PC

dans le fichier app_conf.cnf

tu auras alors le menu fixe et PureC tout seul à l'écran, c'est une option qui permet de faire fonctionner les applis qui se croient un peu toutes seules qui ne fonctionneraient pas correctement sans.

**Comment by vinz6751** [comment]
@Landemarre puis-je suggérer d'ajouter cela dans le fichier "app_conf.cnf" fourni par défaut, avec un commentaire pourquoi la ligne a été ajoutée ?

**Comment by Landemarre** [comment]
Le soucis n'apparait que si on a un menu rétractable, je pense que c'est PureC qui dessine cette ligne en aucun cas l'AES

Si cela est une gène 2 solutions sont possibles:
- Soit on demande d'avoir les menus traditionnels qui ne se rétractent pas, cela peut être fait dans myaes.cnf avec l'option: flying_menu=false
- Soit on suggère de lancer PureC comme une application qui doit se trouver seule sur le bureau comme en monotâche en ajoutant dans app_conf.cnf l'option: app_single PC

Noter qu'à part ce problème avec PureC ce logiciel ne justifie pas par son comportement de l'isoler à l'écran

**Comment by vinz6751** [comment]
Oui. MyAES n'est pas en faute et propose des solutions de contournement, je pense que ce problème peut être fermé.
