### ISSUE TITLE
Police sacrabouillées dans les group box des Window Settings de TosWin2

### ISSUE THREAD

**Issue by vinz6751** [Landemarre/MyAES#7]
MyAES 24-Jan-2021 22:56
Quand on va dans TosWin2, Window settings la police des "group box' affiche apparement n'importe quoi:

![image](https://user-images.githubusercontent.com/9577963/105898928-50720d00-601a-11eb-8d04-5fa7dafea9ab.png)

**Comment by Landemarre** [comment]
Chez moi je n'ai pas exactement cela, j'ai une fonte étrange, je suis surpris, je vais regarder
![bug7](https://user-images.githubusercontent.com/25240527/105916550-60e1b200-6031-11eb-9204-7d6e45db672b.png)

**Comment by Landemarre** [comment]
A priori c'est à cause de la taille de fonte demandée, il doit manquer des fontes dans ta config, XaAES a aussi la même taille de fonte sur une autre de mes configs, je ne pense pas qu'il y ai un bug ici côté MyAES, je vais voir si par hasard le chnagement de taille ne renvérais pas un code erreur

**Comment by Landemarre** [comment]
Je pense que ce coup ci c'est réglé

![toswin2font](https://user-images.githubusercontent.com/25240527/112869738-c435a200-90bd-11eb-99c0-4c6d30060119.png)

**Comment by vinz6751** [comment]
Ah oui c'est joli :) C'était ce que tu pensais au début ?

Le 29/03/2021 à 18:37, Landemarre a écrit :

**Comment by Landemarre** [comment]
Non pas du tout, le problème semble être dans la demande de taille caractère, maintenant je passe par vst_point au lieu de vst_height

**Comment by Landemarre** [comment]
Problème résolu, oublié de le fermer
