### ISSUE TITLE
Problème de dessin des bordures d'objets

### ISSUE THREAD

**Issue by vinz6751** [Landemarre/MyAES#8]
MyAES du 24-Jan-2021 22:56
J'ai remarqué ça:
![image](https://user-images.githubusercontent.com/9577963/105899401-e86ff680-601a-11eb-865a-7d961bd75248.png)

Alors que sur le TOS:
![image](https://user-images.githubusercontent.com/9577963/105899445-f7ef3f80-601a-11eb-851e-137fc4b175fb.png)

De même quand on compile avec Pure C:
MyAES:
![image](https://user-images.githubusercontent.com/9577963/105899801-6c29e300-601b-11eb-9b1c-90c737b38a5d.png)

Sous TOS l'ombre fonctionne mieux et le texte est centré:
![image](https://user-images.githubusercontent.com/9577963/105899608-2cfb9200-601b-11eb-8c3f-b4717ef4e8ef.png)

**Comment by Landemarre** [comment]
Premier problème, semble que MyAES fasse l'ombrage alors qu'il n'y a pas de cadre! Et il me semble qu'il y ai soulignement et que cela s'arrête au texte.

Second faut que je regarde le type d'objet qui est affiché, j'ai l'air de mettre par défaut le texte sur la gauche au lieu de le centrer, à voir.

**Comment by Landemarre** [comment]
Les objets type BUTTON n'étaient pas centrés, le Compiling est maintenant centré
Pour Teradesk, l'objet a le tag objet 3D et soulignement du texte, pour le tag 3D maintenant celui ci n'est plus pris en compte si le nombre de couleurs est inférieur à 16. Le soulignement reste inchangé qe qui n'est pas tout à fait équivalent au TOS, voici la snap de la nouvelle version
![bug8](https://user-images.githubusercontent.com/25240527/106060771-c3e84d00-60f4-11eb-9e94-ec851b19d75c.png)

**Comment by Landemarre** [comment]
The correction to fix text position in button "compiling" of PureC is not accurate with some objects in Qed. The issue is reopen

**Comment by Landemarre** [comment]
Looks like now it is fixed
